name: EUNL Yearly Holdings

"on":
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow requests python-dateutil

      - name: Clone talsan/ishares (scraper)
        run: git clone --depth 1 https://github.com/talsan/ishares.git vendor/ishares

      - name: Fetch full SWDA holdings history
        run: python vendor/ishares/ishares/sync_etf_downloader.py --outputpath data/ishares SWDA --overwrite

      - name: Select latest snapshot per year (>= 2010)
        run: python scripts/select_yearly_snapshots.py --root data/ishares --etf SWDA --from-year 2010 --outdir exports/eunl_yearly

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eunl_yearly_exports
          path: exports/eunl_yearly

      - name: Commit & push results back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add exports/eunl_yearly summary/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Update EUNL yearly holdings exports"
            git push
          else
            echo "No changes to commit"
          fi
