name: EUNL Yearly Holdings
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Upgrade pip & tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel "setuptools<81"

      - name: Install system deps for lxml
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev

      - name: Clone talsan/ishares
        run: git clone --depth 1 https://github.com/talsan/ishares.git vendor/ishares

      - name: Install ishares requirements
        run: |
          pip install -r vendor/ishares/requirements.txt

      - name: Install extra Python deps
        run: |
          pip install pandas pyarrow requests python-dateutil beautifulsoup4 html5lib
          pip install scrapingbee cloudscraper pandas_market_calendars backports.zoneinfo
          pip install openpyxl xlrd "urllib3<2" "certifi<2021" "chardet<4" "idna<3"

      - name: Run downloader (with retries)
        working-directory: vendor/ishares
        env:
          PYTHONPATH: .
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i/3"
            python -m ishares.sync_etf_downloader --outputpath ../../data/ishares SWDA --overwrite && break
            echo "Retry in 10s"; sleep 10
          done

      - name: List downloaded files (debug)
        run: |
          echo "Top of data/ishares:"
          find data/ishares -maxdepth 6 -type f | head -n 200 || true
          echo "Count of CSVs:"
          find data/ishares -name "asofdate=*.csv" | wc -l || true

      - name: Select latest snapshot per year (>= 2010)
        run: |
          python scripts/select_yearly_snapshots.py --root data/ishares --etf SWDA --from-year 2010 --outdir exports/eunl_yearly

      - name: Upload exports & summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eunl_yearly_exports
          path: |
            exports/eunl_yearly
            summary
          if-no-files-found: warn

      - name: Commit results back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add exports/eunl_yearly summary/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Update EUNL yearly holdings exports"
            git push
          else
            echo "No changes to commit"
          fi
