name: EUNL Yearly Holdings

"on":
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Python 3.8 für alte numpy/lxml Pins des ishares-Repos
      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Upgrade pip & base tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel "setuptools<81"

      # Systemlibs für lxml (falls kein Wheel)
      - name: Install system packages for lxml build
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev

      - name: Clone talsan/ishares (scraper)
        run: git clone --depth 1 https://github.com/talsan/ishares.git vendor/ishares

      - name: Install ishares requirements
        run: |
          pip install -r vendor/ishares/requirements.txt

      - name: Install extra Python deps
        run: |
          pip install pandas pyarrow requests python-dateutil beautifulsoup4 html5lib

      - name: Show repo tree before download (debug)
        run: |
          pwd
          ls -la
          ls -la vendor/ishares || true
          ls -la vendor/ishares/ishares || true

      # Downloader mit gesetztem PYTHONPATH ausführen, damit "config" gefunden wird
      - name: Fetch full SWDA holdings history
        env:
          PYTHONPATH: vendor/ishares
        run: |
          python -m ishares.sync_etf_downloader --outputpath data/ishares SWDA --overwrite

      - name: List downloaded files (debug)
        run: |
          echo "Listing data/ishares..."
          find data/ishares -maxdepth 5 -type f | head -n 100 || true
          echo "Count of CSVs:"
          find data/ishares -name "asofdate=*.csv" | wc -l || true

      - name: Select latest snapshot per year (>= 2010)
        run: |
          python scripts/select_yearly_snapshots.py \
            --root data/ishares \
            --etf SWDA \
            --from-year 2010 \
            --outdir exports/eunl_yearly

      - nam
